spring:
  profiles:
    active: 'default'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
    schema:
      - classpath:db/schema_drop.sql
      - classpath:db/schema.sql
    data:
      - classpath:db/schema_data.sql

server:
  port: 8080
  servlet:
    context-path: /

memcacheddemo:
  memcache:
    servers: 127.0.0.1:11211
    weights: 5
    initConn: 20
    minConn: 10
    maxConn: 50
    maintSleep: 3000
    nagle: false
    socketTO: 3000